src/pretty.rs, tests/assets/unit/markup/raw.typ, tests/snapshots/assets__check_file@unit-markup-raw.typ-120.snap, tests/snapshots/assets__check_file@unit-markup-raw.typ-40.snap, tests/snapshots/assets__check_file@unit-markup-raw.typ-80.snap
=> fix: inline raw with lang tag

src/lib.rs, src/main.rs, src/prop.rs, tests/snapshots/assets__check_file@unit-comment-comment-in-if.typ-120.snap, tests/snapshots/assets__check_file@unit-comment-comment-in-if.typ-40.snap, tests/snapshots/assets__check_file@unit-comment-comment-in-if.typ-80.snap
=> feat: skip broken input

src/prop.rs, tests/assets/unit/markup/raw-in-funccall.typ, tests/snapshots/assets__check_file@unit-markup-raw-in-funccall.typ-120.snap, tests/snapshots/assets__check_file@unit-markup-raw-in-funccall.typ-40.snap, tests/snapshots/assets__check_file@unit-markup-raw-in-funccall.typ-80.snap
=> fix: no format multiline single backtick raw

src/attr.rs, src/pretty/mod.rs, tests/assets/unit/code/multiline-string.typ, tests/snapshots/assets__check_file@unit-code-multiline-string.typ-120.snap, tests/snapshots/assets__check_file@unit-code-multiline-string.typ-40.snap, tests/snapshots/assets__check_file@unit-code-multiline-string.typ-80.snap
=> chore: correctly handle multiline string

README.md, src/lib.rs, src/main.rs, tests/assets.rs, tests/repo-e2e.rs
=> refactor: accept `Source` as input and make docs better

src/pretty/mod.rs, tests/assets/unit/comment/comment-in-func-call.typ, tests/snapshots/assets__check_file@unit-comment-comment-in-func-call.typ-120.snap, tests/snapshots/assets__check_file@unit-comment-comment-in-func-call.typ-40.snap, tests/snapshots/assets__check_file@unit-comment-comment-in-func-call.typ-80.snap
=> fix: comment loss in set rule

src/pretty/mod.rs, tests/assets/unit/comment/comment-in-closure.typ, tests/snapshots/assets__check_file@unit-comment-comment-in-closure.typ-120.snap, tests/snapshots/assets__check_file@unit-comment-comment-in-closure.typ-40.snap, tests/snapshots/assets__check_file@unit-comment-comment-in-closure.typ-80.snap
=> fix: comment loss in closure definition

src/lib.rs, src/main.rs
=> fix: cli should also strip whitespace

src/pretty/mod.rs, tests/assets/unit/comment/consecutive-comment.typ, tests/assets/unit/comment/line-comment-attach.typ, tests/snapshots/assets__check_file@tablex.typ-120.snap, tests/snapshots/assets__check_file@tablex.typ-40.snap, tests/snapshots/assets__check_file@tablex.typ-80.snap, tests/snapshots/assets__check_file@unit-comment-consecutive-comment.typ-120.snap, tests/snapshots/assets__check_file@unit-comment-consecutive-comment.typ-40.snap, tests/snapshots/assets__check_file@unit-comment-consecutive-comment.typ-80.snap, tests/snapshots/assets__check_file@unit-comment-line-comment-attach.typ-120.snap, tests/snapshots/assets__check_file@unit-comment-line-comment-attach.typ-40.snap, tests/snapshots/assets__check_file@unit-comment-line-comment-attach.typ-80.snap, tests/snapshots/assets__check_file@unit-func-spread.typ-120.snap, tests/snapshots/assets__check_file@unit-func-spread.typ-40.snap, tests/snapshots/assets__check_file@unit-func-spread.typ-80.snap
=> feat: keep line comment attached

Cargo.toml, README.md, src/cli.rs, src/main.rs
=> feat: add format-all subcommand

src/pretty/mod.rs, src/pretty/table.rs, src/pretty/util.rs, tests/assets/unit/grid/array.typ, tests/assets/unit/grid/basic.typ, tests/assets/unit/grid/cell.typ, tests/assets/unit/grid/extra-arg.typ, tests/snapshots/assets__check_file@undergraduate-math.typ-120.snap, tests/snapshots/assets__check_file@undergraduate-math.typ-40.snap, tests/snapshots/assets__check_file@undergraduate-math.typ-80.snap, tests/snapshots/assets__check_file@unit-grid-array.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-array.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-array.typ-80.snap, tests/snapshots/assets__check_file@unit-grid-basic.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-basic.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-basic.typ-80.snap, tests/snapshots/assets__check_file@unit-grid-cell.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-cell.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-cell.typ-80.snap, tests/snapshots/assets__check_file@unit-grid-extra-arg.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-extra-arg.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-extra-arg.typ-80.snap
=> feat: support basic table formatting

src/pretty/table.rs, src/pretty/util.rs, tests/assets/unit/grid/header-footer.typ, tests/snapshots/assets__check_file@unit-grid-array.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-array.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-array.typ-80.snap, tests/snapshots/assets__check_file@unit-grid-cell.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-cell.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-cell.typ-80.snap, tests/snapshots/assets__check_file@unit-grid-header-footer.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-header-footer.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-header-footer.typ-80.snap
hopefully this can fix #78 . But i cannot tell because the author doesn't provide their full code.
=> feat: support format table with function calls and header/footers

docs/architecture.md, docs/limitations.md, mkdocs.yml
=> docs: add limitation and architecture

.pre-commit-hooks.yaml, README.md
This PR adds a [pre-commit](https://pre-commit.com/#new-hooks) hook.
=> chore: add `.pre-commit-hooks.yaml`

CHANGELOG.md, src/pretty/func_call.rs, src/pretty/util.rs, tests/assets/unit/func/func-call-with-newline.typ, tests/snapshots/assets__check_file@unit-func-func-call-with-newline.typ-120.snap, tests/snapshots/assets__check_file@unit-func-func-call-with-newline.typ-40.snap, tests/snapshots/assets__check_file@unit-func-func-call-with-newline.typ-80.snap
=> feat: preserve newline in func call

Cargo.toml, src/cli.rs, src/main.rs
* fix: fix hangling with `-i` only
* feat: don't terminate processing in case of failure
=> feat: return error code upon failure

CHANGELOG.md, src/pretty/table.rs, tests/assets/unit/grid/extra-arg.typ, tests/snapshots/assets__check_file@unit-grid-extra-arg.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-extra-arg.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-extra-arg.typ-80.snap
=> fix: table has extra new line when there is no pos args

docs/limitations.md
```diff
-@typstype off
+@typstyle off
```
#87
=> docs: fix limitations typo

src/main.rs
- **fix: fix wrong path for completion scripts**
Fix issue referenced in <https://github.com/Enter-tainer/typstyle/pull/131#issuecomment-2365456088>
=> fix: fix wrong path for completion scripts

src/pretty/mod.rs, tests/assets/unit/math/delimited.typ, tests/snapshots/assets__check_file@huge-math.typ-0.snap, tests/snapshots/assets__check_file@huge-math.typ-120.snap, tests/snapshots/assets__check_file@huge-math.typ-40.snap, tests/snapshots/assets__check_file@huge-math.typ-80.snap, tests/snapshots/assets__check_file@typstfmt-113-math-indent.typ-0.snap, tests/snapshots/assets__check_file@typstfmt-113-math-indent.typ-40.snap, tests/snapshots/assets__check_file@typstfmt-113-math-indent.typ-80.snap, tests/snapshots/assets__check_file@typstfmt-137-math-align-panic.typ-0.snap, tests/snapshots/assets__check_file@undergraduate-math.typ-0.snap, tests/snapshots/assets__check_file@undergraduate-math.typ-40.snap, tests/snapshots/assets__check_file@unit-math-attach.typ-0.snap, tests/snapshots/assets__check_file@unit-math-brace-space.typ-0.snap, tests/snapshots/assets__check_file@unit-math-complex-math.typ-0.snap, tests/snapshots/assets__check_file@unit-math-complex-math.typ-120.snap, tests/snapshots/assets__check_file@unit-math-complex-math.typ-40.snap, tests/snapshots/assets__check_file@unit-math-complex-math.typ-80.snap, tests/snapshots/assets__check_file@unit-math-delimited.typ-0.snap, tests/snapshots/assets__check_file@unit-math-delimited.typ-120.snap, tests/snapshots/assets__check_file@unit-math-delimited.typ-40.snap, tests/snapshots/assets__check_file@unit-math-delimited.typ-80.snap, tests/snapshots/assets__check_file@unit-math-equation-flavor.typ-0.snap, tests/snapshots/assets__check_file@unit-math-frac.typ-0.snap, tests/snapshots/assets__check_file@unit-math-long.typ-0.snap, tests/snapshots/assets__check_file@unit-math-long.typ-40.snap, tests/snapshots/assets__check_file@unit-math-primes.typ-0.snap
Since we cannot handle math very well for now, a long line is better than an ugly line.
Let the writer decide whether to break the line.
If this is PR accepted, maybe more tests are needed to ensure structure preservation.
=> feat: do not add extra newlines to math delimited

CHANGELOG.md, Cargo.lock, Cargo.toml
=> chore: bump to v0.12.2

CHANGELOG.md, Cargo.lock, Cargo.toml, src/lib.rs
=> fix: remove doc test and bump to v0.12.3

CHANGELOG.md, Cargo.lock, Cargo.toml
cc @QuadnucYard Please take a look at the changelog. Thanks!
=> chore: bump to v0.12.5

CHANGELOG.md, Cargo.lock, Cargo.toml
=> chore: bump to v0.12.7

src/lib.rs
=> feat: always add end of file newline

crates/typstyle-core/benches/pretty_print.rs, crates/typstyle-core/src/lib.rs, crates/typstyle-core/src/pretty/code_chain.rs, crates/typstyle-core/src/pretty/config.rs, crates/typstyle-core/src/pretty/func_call.rs, crates/typstyle-core/src/pretty/mod.rs, crates/typstyle/src/main.rs, tests/fixtures/packages/snap/cetz-manual.typ-40.snap, tests/fixtures/packages/snap/cetz-tree.typ-120.snap, tests/fixtures/packages/snap/cetz-tree.typ-40.snap, tests/fixtures/packages/snap/cetz-tree.typ-80.snap, tests/fixtures/packages/snap/codly.typ-40.snap, tests/fixtures/packages/snap/fletcher-diagram.typ-40.snap, tests/fixtures/packages/snap/fletcher-draw.typ-120.snap, tests/fixtures/packages/snap/fletcher-draw.typ-40.snap, tests/fixtures/packages/snap/fletcher-draw.typ-80.snap, tests/fixtures/packages/snap/tablex.typ-40.snap, tests/fixtures/packages/snap/tablex.typ-80.snap, tests/fixtures/packages/snap/tidy-new-parser.typ-40.snap, tests/fixtures/packages/snap/tidy-new-parser.typ-80.snap, tests/fixtures/packages/touying/snap/core.typ-40.snap, tests/fixtures/packages/touying/snap/core.typ-80.snap, tests/fixtures/packages/touying/snap/utils.typ-40.snap, tests/fixtures/unit/code/show-chain.typ, tests/fixtures/unit/code/snap/show-chain.typ-0.snap, tests/fixtures/unit/code/snap/show-chain.typ-120.snap, tests/fixtures/unit/code/snap/show-chain.typ-40.snap, tests/fixtures/unit/code/snap/show-chain.typ-80.snap
If a dot chain (without comments) starts with an ident, ends with a func call (no other calls inside), and the chain length (estimated from idents length) does not exceed 60% of max-width, the idents will not break into multiple lines.
=> feat: do not break short dot chains

CHANGELOG.md, Cargo.lock, Cargo.toml
Merge #190 before merging this
=> chore: bump to v0.12.12

.github/workflows/test-and-release.yml
Reverts Enter-tainer/typstyle#204
=> Revert "ci: add build attest"

README.md
=> docs: add archlinux cn

CHANGELOG.md, Cargo.lock, Cargo.toml
=> chore: bump to v0.12.15

crates/typstyle-core/src/config.rs
=> feat: add method to set wrap text option in Config

crates/typstyle-core/src/pretty/layout/list.rs, tests/fixtures/unit/code/func_call_multiline.typ, tests/fixtures/unit/code/snap/func_call_multiline.typ-0.snap, tests/fixtures/unit/code/snap/func_call_multiline.typ-120.snap, tests/fixtures/unit/code/snap/func_call_multiline.typ-40.snap, tests/fixtures/unit/code/snap/func_call_multiline.typ-80.snap
=> fix: multiline function call doesn't converge

crates/typstyle-core/src/pretty/markup.rs, tests/fixtures/unit/markup/reflow/code.typ, tests/fixtures/unit/markup/reflow/commented.typ, tests/fixtures/unit/markup/reflow/exclusive.typ, tests/fixtures/unit/markup/reflow/general.typ, tests/fixtures/unit/markup/reflow/snap/code.typ-0.snap, tests/fixtures/unit/markup/reflow/snap/code.typ-120.snap, tests/fixtures/unit/markup/reflow/snap/code.typ-40.snap, tests/fixtures/unit/markup/reflow/snap/code.typ-80.snap, tests/fixtures/unit/markup/reflow/snap/commented.typ-0.snap, tests/fixtures/unit/markup/reflow/snap/commented.typ-120.snap, tests/fixtures/unit/markup/reflow/snap/commented.typ-40.snap, tests/fixtures/unit/markup/reflow/snap/commented.typ-80.snap, tests/fixtures/unit/markup/reflow/snap/exclusive.typ-0.snap, tests/fixtures/unit/markup/reflow/snap/exclusive.typ-120.snap, tests/fixtures/unit/markup/reflow/snap/exclusive.typ-40.snap, tests/fixtures/unit/markup/reflow/snap/exclusive.typ-80.snap, tests/fixtures/unit/markup/reflow/snap/general.typ-0.snap, tests/fixtures/unit/markup/reflow/snap/general.typ-120.snap, tests/fixtures/unit/markup/reflow/snap/general.typ-40.snap, tests/fixtures/unit/markup/reflow/snap/general.typ-80.snap, tests/fixtures/unit/markup/reflow/snap/unicode.typ-0.snap, tests/fixtures/unit/markup/reflow/snap/unicode.typ-120.snap, tests/fixtures/unit/markup/reflow/snap/unicode.typ-40.snap, tests/fixtures/unit/markup/reflow/snap/unicode.typ-80.snap, tests/fixtures/unit/markup/reflow/unicode.typ
=> fix: do not soft wrap after labels

crates/typstyle-core/src/pretty/math_align.rs, tests/fixtures/unit/math/aligned/impression.typ, tests/fixtures/unit/math/aligned/snap/commented.typ-120.snap, tests/fixtures/unit/math/aligned/snap/commented.typ-40.snap, tests/fixtures/unit/math/aligned/snap/commented.typ-80.snap, tests/fixtures/unit/math/aligned/snap/impression.typ-0.snap, tests/fixtures/unit/math/aligned/snap/impression.typ-120.snap, tests/fixtures/unit/math/aligned/snap/impression.typ-40.snap, tests/fixtures/unit/math/aligned/snap/impression.typ-80.snap, tests/fixtures/unit/math/aligned/snap/multiline-str.typ-120.snap, tests/fixtures/unit/math/aligned/snap/multiline-str.typ-40.snap, tests/fixtures/unit/math/aligned/snap/multiline-str.typ-80.snap, tests/fixtures/unit/math/aligned/snap/multiline.typ-120.snap, tests/fixtures/unit/math/aligned/snap/multiline.typ-40.snap, tests/fixtures/unit/math/aligned/snap/multiline.typ-80.snap, tests/fixtures/unit/math/aligned/snap/nested.typ-120.snap, tests/fixtures/unit/math/aligned/snap/nested.typ-40.snap, tests/fixtures/unit/math/aligned/snap/nested.typ-80.snap, tests/fixtures/unit/math/aligned/snap/unicode.typ-120.snap, tests/fixtures/unit/math/aligned/snap/unicode.typ-40.snap, tests/fixtures/unit/math/aligned/snap/unicode.typ-80.snap, tests/fixtures/unit/math/snap/complex-math.typ-120.snap, tests/fixtures/unit/math/snap/complex-math.typ-80.snap
=> feat: calculate column width solely based on the last line of cells in math align

crates/typstyle-core/src/lib.rs, crates/typstyle-core/src/pretty/code_chain.rs, crates/typstyle-core/src/pretty/code_flow.rs, crates/typstyle-core/src/pretty/code_list.rs, crates/typstyle-core/src/pretty/code_misc.rs, crates/typstyle-core/src/pretty/comment.rs, crates/typstyle-core/src/pretty/func_call.rs, crates/typstyle-core/src/pretty/import.rs, crates/typstyle-core/src/pretty/layout/chain.rs, crates/typstyle-core/src/pretty/layout/flow.rs, crates/typstyle-core/src/pretty/layout/list.rs, crates/typstyle-core/src/pretty/layout/plain.rs, crates/typstyle-core/src/pretty/layout/table.rs, crates/typstyle-core/src/pretty/markup.rs, crates/typstyle-core/src/pretty/math.rs, crates/typstyle-core/src/pretty/math_align.rs, crates/typstyle-core/src/pretty/mod.rs, crates/typstyle-core/src/pretty/parened_expr.rs, crates/typstyle-core/src/pretty/prelude.rs, crates/typstyle-core/src/pretty/table.rs, crates/typstyle-core/src/pretty/text.rs
prepare for switching to customized pretty.rs
=> refactor: add prelude for pretty related

crates/typstyle-core/src/pretty/markup.rs, tests/fixtures/unit/code/snap/if-chain.typ-120.snap, tests/fixtures/unit/code/snap/if-chain.typ-40.snap, tests/fixtures/unit/code/snap/if-chain.typ-80.snap, tests/fixtures/unit/markup/reflow/snap/spaces.typ-0.snap, tests/fixtures/unit/markup/reflow/snap/spaces.typ-120.snap, tests/fixtures/unit/markup/reflow/snap/spaces.typ-40.snap, tests/fixtures/unit/markup/reflow/snap/spaces.typ-80.snap, tests/fixtures/unit/markup/reflow/spaces.typ, tests/fixtures/unit/markup/snap/spaces.typ-0.snap, tests/fixtures/unit/markup/snap/spaces.typ-120.snap, tests/fixtures/unit/markup/snap/spaces.typ-40.snap, tests/fixtures/unit/markup/snap/spaces.typ-80.snap, tests/fixtures/unit/markup/snap/strong-space.typ-0.snap, tests/fixtures/unit/markup/snap/strong-space.typ-120.snap, tests/fixtures/unit/markup/snap/strong-space.typ-40.snap, tests/fixtures/unit/markup/snap/strong-space.typ-80.snap, tests/fixtures/unit/markup/spaces.typ, tests/fixtures/unit/math/snap/hashes.typ-0.snap, tests/fixtures/unit/math/snap/hashes.typ-120.snap, tests/fixtures/unit/math/snap/hashes.typ-40.snap, tests/fixtures/unit/math/snap/hashes.typ-80.snap, tests/src/unit.rs
=> feat: do not collapse spaces on both sides of content blocks

docs/book.typ, docs/deps.typ, docs/ebook.typ, docs/pages/changelog.typ, docs/pages/cli-usage.typ, docs/pages/dev-guide.typ, docs/pages/dev-guide/core.typ, docs/pages/dev-guide/documentation.typ, docs/pages/dev-guide/playground.typ, docs/pages/escape-hatch.typ, docs/pages/features.typ, docs/pages/features/code.typ, docs/pages/features/markup.typ, docs/pages/features/math.typ, docs/pages/features/table.typ, docs/pages/installation.typ, docs/pages/introduction.typ, docs/pages/limitations.typ, docs/pages/quick-start.typ, docs/templates/constants.typ, docs/templates/ebook.typ, docs/templates/metadata.typ, docs/templates/page.typ, docs/templates/rules.typ, docs/templates/styles/base.css, docs/templates/styles/callout.css, docs/templates/version.typ
Adapted from tinymist docs, with better modularization.
=> feat(docs): use starlight theme

Cargo.toml
See commit message, this was part of #389.
=> fix: Fix missing manifest key

docs/templates/page.typ, docs/templates/styles/base.css, docs/templates/styles/hypraw.css
- Reduce heading size
- Fix excessive spacing between content-panel siblings and consecutive headings
=> feat(docs): enable copy code features and patch starlight styles

.github/ISSUE_TEMPLATE/bug-report.yml
As title
- Remove `code` and `actual vs expected`
Before submitting, please ensure you've done the following:
=> chore: further simplify bug report

CHANGELOG.md, Cargo.lock, Cargo.toml
As title
- Edit changelog
- Bump version number
- 
Before submitting, please ensure you've done the following:
=> chore: bump to v0.13.17

CHANGELOG.md, playground/.gitignore, playground/package.json, playground/pnpm-lock.yaml, playground/src/Playground.tsx, playground/src/assets/sample-manifest.json, playground/src/components/editor/CodeEditor.tsx, playground/src/components/editor/OutputEditor.tsx, playground/src/components/editor/SourceEditor.tsx, playground/src/components/editor/index.ts, playground/src/components/forms/SampleDocumentSelector.tsx, playground/src/constants.ts, playground/src/styles/theme.css, playground/src/utils/sample-loader.ts, playground/vite.config.ts
- Added some loadable sample documents.
- Changed the indent size of AST/IR editors to 2.
Before submitting, please ensure you've done the following:
=> feat(web): load test fixtures as samples

README.md
Now the link in README points to the current roadmap.
Is the title ok?
=> chore: update link to the roadmap in README
