typstyle-rs/typstyle

web/src/main.ts, web/src/style.css
=> feat: add convergent test in webapp

src/prop.rs
=> fix: no format math nodes that has hash child

src/pretty/func_call.rs, src/pretty/mod.rs, src/pretty/table.rs, src/pretty/util.rs, tests/assets/unit/grid/colspan.typ, tests/snapshots/assets__check_file@cetz-manual.typ-120.snap, tests/snapshots/assets__check_file@cetz-manual.typ-40.snap, tests/snapshots/assets__check_file@cetz-manual.typ-80.snap, tests/snapshots/assets__check_file@tablex.typ-40.snap, tests/snapshots/assets__check_file@undergraduate-math.typ-120.snap, tests/snapshots/assets__check_file@undergraduate-math.typ-40.snap, tests/snapshots/assets__check_file@undergraduate-math.typ-80.snap, tests/snapshots/assets__check_file@unit-code-func-call-flavor.typ-120.snap, tests/snapshots/assets__check_file@unit-code-func-call-flavor.typ-40.snap, tests/snapshots/assets__check_file@unit-code-func-call-flavor.typ-80.snap, tests/snapshots/assets__check_file@unit-grid-cell.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-cell.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-cell.typ-80.snap, tests/snapshots/assets__check_file@unit-grid-colspan.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-colspan.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-colspan.typ-80.snap, tests/snapshots/assets__check_file@unit-markup-content-raw.typ-120.snap, tests/snapshots/assets__check_file@unit-markup-content-raw.typ-40.snap, tests/snapshots/assets__check_file@unit-markup-content-raw.typ-80.snap
This pr keeps call to `table` almost as is when typstyle fails to format it into a rectangle shape. Specifically, this pr will:
1. parse args in `table` to `Vec<OneOf<arg, comment, comma, newline>>`
2. format each arg
3. concat them back
This is useful because currently typstyle cannot further recognize complex col/rowspan and spread patterns. We may simply respect user's decision. Note that previously it will typically put each arg in a line. And that can be frustrating for users.
This PR also make it easier for correctly formating array/dict/funccall with comments and extra newlines.
=> feat: keep table content almost as is if cannot be formatted

Cargo.toml, build.rs, src/cli.rs
When packaging for linux, some distros (e.g. Void Linux) do not use git to obtain package source, but download source archives directly. That makes any git repository info unavailable and currently requires either adding unnecessary libgit2 dependency or patching the code out.
This change allows using `--no-default-features --features=cli,wasm` to disable the git portion if needed.
=> feat(build): allow disabling git info collection

README.md, src/cli.rs, src/main.rs
This PR adds support for CI-related return value policy.
In `--check` mode, typstyle returns 0 (success) only if:
1. ALL files are formatted correctly, and
2. ALL files are unchanged (properly projected).
Otherwise, typstyle will return 1 if, for example:
1. Any failure occurs in formatting any file, or
2. Any file is changed (not well formatted).
This change will not affect the previous return policy when `--check` is not used.
=> feat: add CI check for files changed

.github/workflows/release.yml
Adapt the release artifact names, so that `cargo-binstall` can find `typstyle-{ target }` in github release assets.
Notes:
- `cargo-binstall` sets file-mode for binaries ( https://github.com/cargo-bins/cargo-binstall/blob/76814e4e8feaede87d8d112a4fad519d8eeaf81d/crates/binstalk-bins/src/lib.rs#L218 ), so current permission-loss artifacts simply work well.
=> ci: adapt release for `cargo-binstall`

src/pretty/mod.rs, tests/assets/unit/code/show-closure-paren-complex.typ, tests/assets/unit/code/show-closure-paren.typ, tests/assets/unit/code/single-arg-closure.typ, tests/snapshots/assets__check_file@cetz-manual.typ-120.snap, tests/snapshots/assets__check_file@cetz-manual.typ-40.snap, tests/snapshots/assets__check_file@cetz-manual.typ-80.snap, tests/snapshots/assets__check_file@tablex.typ-120.snap, tests/snapshots/assets__check_file@tablex.typ-40.snap, tests/snapshots/assets__check_file@tablex.typ-80.snap, tests/snapshots/assets__check_file@unit-code-show-closure-paren-complex.typ-120.snap, tests/snapshots/assets__check_file@unit-code-show-closure-paren-complex.typ-40.snap, tests/snapshots/assets__check_file@unit-code-show-closure-paren-complex.typ-80.snap, tests/snapshots/assets__check_file@unit-code-show-closure-paren.typ-120.snap, tests/snapshots/assets__check_file@unit-code-show-closure-paren.typ-40.snap, tests/snapshots/assets__check_file@unit-code-show-closure-paren.typ-80.snap, tests/snapshots/assets__check_file@unit-code-single-arg-closure.typ-120.snap, tests/snapshots/assets__check_file@unit-code-single-arg-closure.typ-40.snap, tests/snapshots/assets__check_file@unit-code-single-arg-closure.typ-80.snap, tests/snapshots/assets__check_file@unit-grid-colspan.typ-120.snap, tests/snapshots/assets__check_file@unit-grid-colspan.typ-40.snap, tests/snapshots/assets__check_file@unit-grid-colspan.typ-80.snap
The surrounding parens are required because currently typst doesn't allow closure body presenting in new line
```
#let f = a =>
a + 1
#f(1)
```
```
Error: expected expression
╭─[/main.typ:8:14]
│
8 │ #let f = a =>
───╯
```
=> feat: put single var closure's body in a new line when closure body is multiline

Cargo.lock, Cargo.toml, src/cli.rs, src/main.rs
Trying to add command-line completions.
Closes #130
=> feature: add command-line completions

src/pretty/func_call.rs, src/pretty/mod.rs, tests/assets/unit/comment/comment-convergence.typ, tests/snapshots/assets__check_file@unit-comment-block-comment.typ-0.snap, tests/snapshots/assets__check_file@unit-comment-block-comment.typ-120.snap, tests/snapshots/assets__check_file@unit-comment-block-comment.typ-40.snap, tests/snapshots/assets__check_file@unit-comment-block-comment.typ-80.snap, tests/snapshots/assets__check_file@unit-comment-comment-convergence.typ-0.snap, tests/snapshots/assets__check_file@unit-comment-comment-convergence.typ-120.snap, tests/snapshots/assets__check_file@unit-comment-comment-convergence.typ-40.snap, tests/snapshots/assets__check_file@unit-comment-comment-convergence.typ-80.snap
fix #136
This a rough fix. Ideally we should get the indent level of the start of the block comment, and strip that specific amount of whitesapce for each line. But this is unfortunately a little bit hard to implement in `typst-syntax`.
This pr unconditionally strips all prefix whitespace for the block comments.
=> fix: the last line of block comment doesn't converge

src/pretty/mod.rs
The benchmark shows that the performance for documents with massive unformattable texts declined significantly in #173.
This PR reverts the method that retrieves text from the source.
=> fix: performance regression from text retrieval

.github/workflows/release.yml
`-crt-static` disables static linked musl, which is unintended
=> ci: fix musl build

Cargo.lock, Cargo.toml, build.rs
Resolves 3 vulnerability issues and bumps `vergen` to 9.0.
=> build: update deps and resolve security issues

crates/typstyle-core/src/attr.rs, crates/typstyle-core/src/pretty/code_list.rs, tests/fixtures/unit/off/after-hash.typ, tests/fixtures/unit/off/block-single.typ, tests/fixtures/unit/off/snap/after-hash.typ-0.snap, tests/fixtures/unit/off/snap/after-hash.typ-120.snap, tests/fixtures/unit/off/snap/after-hash.typ-40.snap, tests/fixtures/unit/off/snap/after-hash.typ-80.snap, tests/fixtures/unit/off/snap/block-single.typ-0.snap, tests/fixtures/unit/off/snap/block-single.typ-120.snap, tests/fixtures/unit/off/snap/block-single.typ-40.snap, tests/fixtures/unit/off/snap/block-single.typ-80.snap, tests/fixtures/unit/off/snap/through.typ-0.snap, tests/fixtures/unit/off/snap/through.typ-120.snap, tests/fixtures/unit/off/snap/through.typ-40.snap, tests/fixtures/unit/off/snap/through.typ-80.snap, tests/fixtures/unit/off/through.typ
Fixes #182:
- If `@typstyle off` appears before the first expression in a code block, it will not take effect, since this comment is not inside the `Code` that expressions lie in.
- `@typstyle off` does not apply to the expression after hash (`#`).
=> fix: escape hatch not effective in some cases

crates/typstyle-core/benches/pretty_print.rs, crates/typstyle-core/src/lib.rs, crates/typstyle-core/src/pretty/chain.rs, crates/typstyle-core/src/pretty/config.rs, crates/typstyle-core/src/pretty/func_call.rs, crates/typstyle-core/src/pretty/list.rs, crates/typstyle-core/src/pretty/markup.rs, crates/typstyle-core/src/pretty/mod.rs, crates/typstyle-core/src/pretty/parened_expr.rs, crates/typstyle-core/src/pretty/table.rs, crates/typstyle/src/main.rs, tests/src/repo-e2e.rs, tests/src/unit.rs
Although we do not mean to expose `tab_spaces` to CLI users at the moment, it is fine to use configurable values instead of magic numbers. This can also benefit lib users.
Considering that we may add more printing methods to `Typstyle` (in the upcoming partial formatting), which all require configs, I think it is better to replace the existing `width` param with config for extensibility. This is an API break.
=> refactor: create Typstyle with config and get tab spaces from config

Cargo.lock, crates/typstyle-core/benches/pretty_print.rs, crates/typstyle-core/src/lib.rs, crates/typstyle/src/cli.rs, crates/typstyle/src/fmt.rs, crates/typstyle/src/main.rs, tests/Cargo.toml, tests/fixtures/typstfmt/snap/148-broken-input.typ-0.snap, tests/fixtures/typstfmt/snap/148-broken-input.typ-120.snap, tests/fixtures/typstfmt/snap/148-broken-input.typ-40.snap, tests/fixtures/typstfmt/snap/148-broken-input.typ-80.snap, tests/src/repo-e2e.rs, tests/src/unit.rs
- (API change) Now `Typstyle::pretty_print` returns `Result<String, FormatError>` instead of `String`.  We will have similar APIs in the upcoming partial formatting. WASM API is unchanged.
- (fix) Compilation error with WASM API introduced in #194.
- (test) Input with errors is marked erroneous in info.
- (refactor) Organize CLI format code.
- (perf) Avoid writing back if unchanged. Avoid cloning the original text if it is erroneous.
Input with error is kept accepted in check mode.
We noticed that files are still formatted even in check mode. This will be handled in the next PR.
=> feat: emit error if source is erroneous instead of silence

Cargo.lock, Cargo.toml, README.md, crates/typstyle-core/Cargo.toml, crates/typstyle/Cargo.toml, crates/typstyle/src/cli.rs, crates/typstyle/src/fmt.rs, crates/typstyle/src/logging.rs, crates/typstyle/src/main.rs
- (feature) Add simple logging. Verbosity can be customized.
- (feature) Validate args before execution. `--inplace` conflicts with `--check`. `--inplace` with no input is rejected.
- (feature) Display duration in `format-all` command.
- (fix) Run with `--check` now will not modify files.
- (fix) `format-all` command now correctly has `--column` and `--check` args.
- (fix) Missing readme in crates.
- (chore) Update CLI usage in README.
=> fix: cli check behavior and format-all args

crates/typstyle/src/fmt.rs, crates/typstyle/tests/test_format.rs, crates/typstyle/tests/test_format_stdin.rs
As discussed in #205, this PR fixes the printing and prevent typstyle from adding unintended additional end-of-file newlines.
=> fix: do not add additional end-of-file newline

crates/typstyle-core/src/config.rs, crates/typstyle/src/cli.rs, crates/typstyle/src/fmt.rs, crates/typstyle/tests/test_format_all.rs
This PR closes #116 and #122.
Although `typstyle` is opinionated, tab width is a common setting to expose to the user in other opinionated formatters.
=> Add `--tab-width`, which sets number of spaces for levels of indentation in the output

crates/typstyle/src/fmt.rs, crates/typstyle/tests/test_format.rs, crates/typstyle/tests/test_format_all.rs, crates/typstyle/tests/test_format_stdin.rs
Fixes #218.
Prints the source when the source is erroneous, if not in check or inplace mode.
No change to error code.
=> fix: no output when the source is erroneous

crates/typstyle-core/src/pretty/func_call.rs, crates/typstyle-core/src/pretty/markup.rs, crates/typstyle-core/src/pretty/mod.rs, crates/typstyle-core/src/pretty/parened_expr.rs
Perhaps the performance can improve a bit.
It is `group` rather than `flat_alt` that really hurts.
=> dev: remove unnecessary grouping

crates/typstyle-core/src/pretty/code_flow.rs, crates/typstyle-core/src/pretty/parened_expr.rs, tests/fixtures/packages/snap/codly.typ-0.snap, tests/fixtures/packages/snap/fletcher-diagram.typ-0.snap, tests/fixtures/packages/snap/fletcher-diagram.typ-40.snap, tests/fixtures/packages/snap/fletcher-diagram.typ-80.snap, tests/fixtures/packages/snap/fletcher-draw.typ-0.snap, tests/fixtures/packages/snap/fletcher-draw.typ-40.snap, tests/fixtures/packages/snap/tablex.typ-0.snap, tests/fixtures/packages/touying/snap/core.typ-0.snap, tests/fixtures/packages/touying/snap/utils.typ-0.snap, tests/fixtures/typstfmt/snap/82-non-converge-list.typ-0.snap, tests/fixtures/unit/chain/snap/binary-0.typ-0.snap, tests/fixtures/unit/chain/snap/call.typ-0.snap, tests/fixtures/unit/code/snap/closure-simple.typ-0.snap, tests/fixtures/unit/code/snap/perf-nest.typ-0.snap, tests/fixtures/unit/code/snap/show-chain.typ-0.snap, tests/fixtures/unit/comment/snap/in-closure.typ-0.snap, tests/fixtures/unit/comment/snap/in-closure.typ-40.snap, tests/fixtures/unit/comment/snap/in-showset.typ-0.snap, tests/fixtures/unit/func/snap/func_call.typ-0.snap, tests/fixtures/unit/func/snap/spread.typ-0.snap
Use braces (`{}`) instead of parens (`()`) when the closure body is not a chainable binary expression. e.g.
```typst
#fun(() => {
aaa
})
instead of
#fun(() => (
aaa
))
```
Braces are more intuitive and align with the behavior of other languages.
I exclude binary expressions to avoid double nesting.
PERFORMANCE CONSIDERATION: The code block has extra evaluation burden.
=> feat: use braces instead of parentheses for multiline closure bodies

.github/workflows/test-and-release.yml, Cargo.lock, Cargo.toml, crates/typstyle-consistency/Cargo.toml, crates/typstyle-consistency/src/cmp.rs, crates/typstyle-consistency/src/universe.rs
Drops `reflexo-typst`, which is used for readable diag messages.
=> build: replace reflexo with tinymist-world 0.13.2

README.md
Hey! I thought it would be convenient, so I wrote up a GitHub Action for typstyle and wanted to add it to the README.
[typstyle-action](https://github.com/grayespinoza/typstyle-action)
=> Add typstyle-action GitHub Action to README

crates/typstyle-core/src/config.rs, crates/typstyle-core/src/pretty/code_list.rs, crates/typstyle-core/src/pretty/import.rs, crates/typstyle/src/cli.rs, crates/typstyle/src/fmt.rs, crates/typstyle/tests/test_format_all.rs, crates/typstyle/tests/test_style_args.rs, tests/fixtures/unit/code/import-reorder.typ, tests/fixtures/unit/code/snap/import-reorder.typ-0.snap, tests/fixtures/unit/code/snap/import-reorder.typ-120.snap, tests/fixtures/unit/code/snap/import-reorder.typ-40.snap, tests/fixtures/unit/code/snap/import-reorder.typ-80.snap, tests/src/common.rs, tests/src/unit.rs
Add an option to reorder import items (default: false). Part of #212.
We sort the items of an import statement alphabetically, if it has no comment or duplicated name. In other cases, the order should not matter.
We designed a directive to set local configuration in different unit tests: `/// typstyle: some-options`.
=> feat: reorder import items if no comment or duplication

crates/typstyle-consistency/src/cmp.rs, crates/typstyle-consistency/src/harness.rs, tests/src/unit.rs
if env `TYPSTYLE_SAVE_DIFF` is set, save pngs to that directory when the outputs are inconsistent.
=> test: optionally save diff PNGs to given directory

crates/typstyle-core/src/pretty/code_flow.rs, crates/typstyle-core/src/pretty/func_call.rs, crates/typstyle-core/src/pretty/import.rs, crates/typstyle-core/src/pretty/markup.rs, crates/typstyle-core/src/pretty/math.rs, tests/fixtures/unit/math/attach-hash.typ, tests/fixtures/unit/math/snap/attach-hash.typ-0.snap, tests/fixtures/unit/math/snap/attach-hash.typ-120.snap, tests/fixtures/unit/math/snap/attach-hash.typ-40.snap, tests/fixtures/unit/math/snap/attach-hash.typ-80.snap
Fixes #272.
In tests, added a directive to bypass unnecessary testcases. Old fixtures not updated yet.
=> fix: do not eat space between hashed expr and math underscore

Cargo.lock, Cargo.toml, README.md, crates/typstyle-core/src/lib.rs, crates/typstyle/Cargo.toml, crates/typstyle/src/cli.rs, crates/typstyle/src/fmt.rs, crates/typstyle/src/fs.rs, crates/typstyle/src/main.rs, crates/typstyle/tests/common.rs, crates/typstyle/tests/test_format.rs, crates/typstyle/tests/test_format_all.rs
Now the CLI can accept a list of mixed files and directories, instead of files only.
Deprecated the `format-all` command, which can be covered by `typstyle <dir>`.
Bug fix: Directories with paths containing `.` or `..` were not formatted before.
Changes to CLI args:
- `--column`/`-c` renamed to `--line-width`/`-l`. 
- `--tab-width` renamed to `--indent-width`.
Old names are kept as aliases for compatibility.
=> feat(cli): support formatting multiple directories and deprecate `format-all` command

crates/typstyle-core/src/pretty/markup.rs, tests/fixtures/packages/quill-gallery.typ, tests/fixtures/packages/snap/quill-gallery.typ-0.snap, tests/fixtures/packages/snap/quill-gallery.typ-120.snap, tests/fixtures/packages/snap/quill-gallery.typ-40.snap, tests/fixtures/packages/snap/quill-gallery.typ-80.snap, tests/fixtures/unit/markup/reflow/exclusive.typ, tests/fixtures/unit/markup/reflow/snap/exclusive.typ-0.snap, tests/fixtures/unit/markup/reflow/snap/exclusive.typ-120.snap, tests/fixtures/unit/markup/reflow/snap/exclusive.typ-40.snap, tests/fixtures/unit/markup/reflow/snap/exclusive.typ-80.snap
improvement of #286
respect intended linebreak syntax in the middle of a line, especially in inline markup blocks.
=> fix: do not always break after `\`

crates/typstyle-core/src/attr.rs, crates/typstyle-core/src/pretty/code_misc.rs, tests/fixtures/unit/off/complex.typ, tests/fixtures/unit/off/snap/complex.typ-0.snap, tests/fixtures/unit/off/snap/complex.typ-120.snap, tests/fixtures/unit/off/snap/complex.typ-40.snap, tests/fixtures/unit/off/snap/complex.typ-80.snap, tests/fixtures/unit/off/snap/through.typ-0.snap, tests/fixtures/unit/off/snap/through.typ-120.snap, tests/fixtures/unit/off/snap/through.typ-40.snap, tests/fixtures/unit/off/snap/through.typ-80.snap, tests/fixtures/unit/off/through.typ
- Previously, escape hatch does not work for:
- ArrayItem
- DictItem
- Param
- DestructuringItem
Now it is fixed.
- `@typstyle off` no longer penetrates comments.
- Previously, if `@typstyle off` appears before Code or Math, it applies to the whole syntax node. Now it only applies to its first non-trivial child.
=> fix: bad escape hatch in corner cases

README.md, crates/typstyle/src/cli.rs, crates/typstyle/src/fmt.rs
A useful feature for developers and users to observe its performance.
The parsing time is not included.
Example:
```
$ typstyle a.typ --check --timing
Formatting completed in 109.4µs
Would reformat: a.typ
```
=> feat(cli): add timing option to show elapsed time for formatting

.github/workflows/bench-pr.yml, .github/workflows/gh-pages.yml, .github/workflows/test-and-release.yml
Todo later: do not run tests when changes do not touch rust lib, but ensure releasing work.
Something like this, but need fine-grained skip check in individual jobs.
```yml
- id: skip_check
uses: fkirc/skip-duplicate-actions@v5
with:
cancel_others: "true"
paths: |
- "Cargo.toml"
- "Cargo.lock"
- "crates/**"
- "tests/**"
- ".github/workflows/test-and-release.yml"
```
=> ci: improve triggers and permissions in workflows

README.md
Updates `grayespinoza` reference in GitHub Action section of`README.md` to `typstyle-rs`.
As long as I have a personal fork of the GitHub Action, it'll redirect to mine instead of the actual action.
=> fix: update grayespinoza to typstyle-rs

CHANGELOG.md, crates/typstyle-core/src/pretty/args.rs, crates/typstyle-core/src/pretty/code_chain.rs, crates/typstyle-core/src/pretty/code_flow.rs, crates/typstyle-core/src/pretty/func_call.rs, crates/typstyle-core/src/pretty/table.rs, crates/typstyle-core/src/pretty/util.rs, tests/fixtures/unit/code/set-rule.typ, tests/fixtures/unit/code/snap/set-rule.typ-0.snap, tests/fixtures/unit/code/snap/set-rule.typ-120.snap, tests/fixtures/unit/code/snap/set-rule.typ-40.snap, tests/fixtures/unit/code/snap/set-rule.typ-80.snap, tests/fixtures/unit/table/empty.typ, tests/fixtures/unit/table/recognize.typ, tests/fixtures/unit/table/snap/empty.typ-0.snap, tests/fixtures/unit/table/snap/empty.typ-120.snap, tests/fixtures/unit/table/snap/empty.typ-40.snap, tests/fixtures/unit/table/snap/empty.typ-80.snap, tests/fixtures/unit/table/snap/recognize.typ-0.snap, tests/fixtures/unit/table/snap/recognize.typ-120.snap, tests/fixtures/unit/table/snap/recognize.typ-40.snap, tests/fixtures/unit/table/snap/recognize.typ-80.snap
- Bug fix: In code mode, `std.table` was not recognized as a table function, preventing proper table formatting.
- Bug fix: Fixed incorrect formatting of table functions with empty content blocks.
When `table.header` or `table.footer` had no no parentheses (`()`), the formatter would incorrectly add parentheses before empty content blocks. When parenthesized args are empty, the formatter would insert an line break with short line length. closes #349 
For example:
```typst
#table(
columns: 2,
table.header[],
table.footer(),
)
```
was formatted to:
```typst
#table(
columns: 2,
table.header()[],
table.footer(),
)
```
or with short line length:
```typst
#table(
columns: 2,
table.header(
)[],
table.footer(
),
)
```
- Bug fix: Fixed incorrect handling of trailing content blocks in set rules. …
=> fix: properly handle parenthesized args and trailing content blocks

.github/workflows/claude.yml, CLAUDE.md
Add CLAUDE.md file to provide guidance for Claude Code instances working with this repository.
https://docs.anthropic.com/en/docs/claude-code/github-actions
Contains:
- Project architecture overview (workspace structure)
- Essential development commands for build, test, and documentation
- Key directories and files for quick navigation
- Testing and benchmark instructions
This helps future Claude Code instances quickly understand the codebase structure and development workflow.
=> docs: add CLAUDE.md for Claude Code guidance

.gitmodules
Change submodule URL from absolute SSH format to relative path format (../../QuadnucYard/typst-hypraw.git) to make it protocol-agnostic.
This allows users to clone the repository without requiring a GitHub account, as the relative URL will resolve correctly regardless of whether HTTPS or SSH is used for the initial clone.
Fixes #347
=> fix: use portable relative URL for git submodule

crates/typstyle-core/src/pretty/comment.rs, tests/fixtures/packages/snap/fletcher-diagram.typ-80.snap, tests/fixtures/packages/snap/fletcher-draw.typ-40.snap, tests/fixtures/packages/snap/fletcher-draw.typ-80.snap, tests/fixtures/packages/snap/tablex.typ-120.snap, tests/fixtures/packages/snap/tablex.typ-40.snap, tests/fixtures/packages/snap/tablex.typ-80.snap, tests/fixtures/unit/markup/reflow/snap/commented.typ-40.snap
WIP: wait for upstream feature stablized
Now line comments no longer take up any space.
Question: should it also apply to trailing block comments?
=> feat: treat line comments as line suffixes

playground/.prettierrc, playground/package.json, playground/pnpm-lock.yaml, playground/src/Playground.tsx, playground/src/components/forms/SettingsPanel.tsx, playground/src/constants.ts, playground/src/hooks/index.ts, playground/src/hooks/use-playground-state.ts, playground/src/hooks/use-typst-formatter.ts, playground/src/hooks/useShareManager.ts, playground/src/types.ts, playground/src/utils/formatter.ts, playground/src/utils/index.ts, playground/src/utils/pastebin.ts, playground/src/utils/url.ts
Now url query params are dynamically updated with format options and code (using lz-string compression). So, we can use the current URL as sharing link and serve the purpose of persistence.
Only code is uploaded to the pastebin when the URL to share is too long.
=> feat(web): persist playground state in url

crates/typstyle-core/src/pretty/markup.rs, crates/typstyle-core/src/pretty/text.rs, tests/fixtures/unit/markup/reflow/general.typ, tests/fixtures/unit/markup/reflow/marker.typ, tests/fixtures/unit/markup/reflow/snap/general.typ-0.snap, tests/fixtures/unit/markup/reflow/snap/general.typ-120.snap, tests/fixtures/unit/markup/reflow/snap/general.typ-40.snap, tests/fixtures/unit/markup/reflow/snap/general.typ-80.snap, tests/fixtures/unit/markup/reflow/snap/marker.typ-0.snap, tests/fixtures/unit/markup/reflow/snap/marker.typ-120.snap, tests/fixtures/unit/markup/reflow/snap/marker.typ-40.snap, tests/fixtures/unit/markup/reflow/snap/marker.typ-80.snap
=> fix: prevent breaking before enum marker-like texts

playground/src/Playground.tsx, playground/src/components/editor/SourceEditor.tsx, playground/src/components/forms/RangeControls.tsx, playground/src/components/ui/StatusBar.tsx, playground/src/components/ui/index.ts, playground/src/hooks/index.ts, playground/src/hooks/use-editor-selection.ts, playground/src/hooks/use-typst-formatter.ts, playground/src/types.ts, playground/src/utils/editor-selection.ts
also added toggle word wrap in the editor
=> feat(web): show output and status of selected range in playground

crates/typstyle-core/src/lib.rs, crates/typstyle-core/src/partial.rs, crates/typstyle-core/src/utils.rs, crates/typstyle-typlugin/Cargo.toml, crates/typstyle-typlugin/src/lib.rs, crates/typstyle-wasm/Cargo.toml, crates/typstyle-wasm/src/lib.rs, crates/typstyle/src/fmt.rs, crates/typstyle/tests/test_format_stdin.rs
make output not too wide
we may need a function to print ast, avoiding duplication of changing indents in wasm bindings
=> feat: change indentation size of AST/IR from 4 to 2
